export var DefaultProps = {
    className: '',
    type: '',
    terms: null,
    buttons: null,
    buttonsFixed: false,
    buttonsDirection: 'vertical',
    termPrefix: '',
    termSuffix: '',
    checkboxTipsText: '',
    checkboxTipsVisible: false,
    readCurrent: null,
    defaultReadCurrent: 0,
    onButtonTap: function () { },
    onTermTap: function () { },
    onCheckChange: function () { },
    onTermPrefixTap: function () { },
    onCountdownFinish: function () { },
    onReadChange: function () { },
};
