export var PickerDefaultProps = {
    formattedValueText: null,
    visible: null,
    defaultVisible: null,
    animationType: 'transform',
    value: null,
    defaultValue: null,
    disabled: false,
    readonly: false,
    title: '',
    okText: null,
    cancelText: null,
    placeholder: null,
    options: [],
    popClassName: '',
    popStyle: '',
    maskClosable: true,
    onFormat: null,
    emptyText: null,
};
